export enum CatalogueTypeEnum {
    users_identification_type = 'users_identification_type',
    users_blood_type = 'users_blood_type',
    users_ethnic_origin = 'users_ethnic_origin',
    users_gender = 'users_gender',
    users_marital_status = 'users_marital_status',
    users_nationality = 'users_nationality',
    users_sex = 'users_sex',
    users_security_question = 'users_security_question',
    processes_state = 'processes_state',
    cadastres_state = 'cadastres_state',
    dpa_zone = 'dpa_zone',
    activities_geographic_area = 'activities_geographic_area',
    internal_zonal_users_zone = 'internal_zonal_users_zone',
    processes_legal_entity = 'processes_legal_entity',
    ctc_activities = 'ctc_activities',
    tourist_transport_companies_type = 'tourist_transport_companies_type',
    cadastre_states_state = 'cadastre_states_state',
    adventure_tourism_modalities = 'adventure_tourism_modalities',
    adventure_tourism_modalities_air = 'adventure_tourism_modalities_air',
    adventure_tourism_modalities_land = 'adventure_tourism_modalities_land',
    adventure_tourism_modalities_water = 'adventure_tourism_modalities_water',
    process_agency_permanent_physical_space = 'process_agency_permanent_physical_space',
    processes_local_type = 'processes_local_type',
    internal_inactivation_causes = 'internal_inactivation_causes',
    inactivation_cause_type = 'inactivation_cause_type',
    complementary_services_model = 'complementary_services_model',
    rooms_room_type = 'rooms_room_type',
    breach_causes = 'breach_causes',
    complementary_services_entity = 'complementary_services_entity',
    activities_types_kitchens_continent = 'activities_types_kitchens_continent',
    activities_type_establishments = 'activities_type_establishments',
    activities_types_services_continent = 'activities_types_services_continent',
    kitchen_types_continent = 'kitchen_types_continent',
    ruc_types = 'ruc_types',
    process_food_drinks_establishment_type = 'process_food_drinks_establishment_type',
    service_types_continent = 'service_types_continent',
    transport_vehicle_types = 'transporte_tipo_vehiculos',
    process_transport_airline_type = 'process_transport_airline_type'
}

export enum CatalogueStateEnum {
    ENABLED = 'enabled',
    DISABLED = 'disabled'
}

export enum CatalogueInspectionsStateEnum {
    autogenerated_1 = 'autogenerated_1',
    autogenerated_2 = 'autogenerated_2',
    requested = 'requested',
    scheduled = 'scheduled',
    confirmed = 'confirmed',
    rescheduled_1 = 'rescheduled_1',
    rescheduled_2 = 'rescheduled_2'
}

export enum CatalogueProcessesTypeEnum {
    registration = 'registration',
    update = 'update',
    inactivation = 'inactivation',
    new_classification = 'new_classification',
    new_activity = 'new_activity',
    readmission = 'readmission',
    reclassification = 'reclassification',
    recategorization = 'recategorization'
}

export enum CatalogueProcessFoodDrinksEstablishmentTypeEnum {
    cadena = 'cadena',
    franquicia = 'franquicia',
    ninguno = 'ninguno'
}

export enum CatalogueProcessesStateEnum {
    pending_1 = 'pending_1',
    pending_2 = 'pending_2',
    completed = 'completed'
}

export enum CatalogueActivitiesCodeEnum {
    accommodation_continent = 'accommodation_continent',
    accommodation_galapagos = 'accommodation_galapagos',
    agency_continent = 'agency_continent',
    agency_galapagos = 'agency_galapagos',
    ctc_continent = 'ctc_continent',
    ctc_galapagos = 'ctc_galapagos',
    event_continent = 'event_continent',
    event_galapagos = 'event_galapagos',
    food_drink_continent = 'food_drink_continent',
    food_drink_galapagos = 'food_drink_galapagos',
    park_continent = 'park_continent',
    park_galapagos = 'park_galapagos',
    transport_continent = 'transport_continent',
    transport_galapagos = 'transport_galapagos'
}

export enum CatalogueCadastresStateEnum {
    pending = 'pending',
    ratified = 'ratified',
    inactive = 'inactive',
    temporary_suspension = 'temporary_suspension',
    definitive_suspension = 'definitive_suspension',
    recategorized = 'recategorized',
    reclassified = 'reclassified'
}

export enum CatalogueProcessFoodDrinksClassificationEnum {
    cafeteria = 'cafeteria',
    bar = 'bar',
    restaurante = 'restaurante',
    discoteca = 'discoteca',
    plazas_comida = 'plazas_comida',
    establecimiento_movil = 'establecimiento_movil',
    servicio_catering = 'servicio_catering'
}
